// <auto-generated />
using System;
using BudgetHelperClassLibrary.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BudgetHelperClassLibrary.Migrations
{
    [DbContext(typeof(BudgetHelperDbContext))]
    [Migration("20260110223552_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BudgetHelperClassLibrary.Models.BudgetForPurchases", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Period")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BudgetForPurchases");
                });

            modelBuilder.Entity("BudgetHelperClassLibrary.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("BudgetHelperClassLibrary.Models.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpenseDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RecurringExpenseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("BudgetHelperClassLibrary.Models.Income", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("IncomeSourceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReceivedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Incomes");
                });

            modelBuilder.Entity("BudgetHelperClassLibrary.Models.IncomeSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IncomeSources");
                });

            modelBuilder.Entity("BudgetHelperClassLibrary.Models.RecurringExpense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("FrequencyInMonths")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RecurringExpenses");
                });

            modelBuilder.Entity("CategoryExpense", b =>
                {
                    b.Property<int>("CategoryListId")
                        .HasColumnType("int");

                    b.Property<int>("ExpensesListId")
                        .HasColumnType("int");

                    b.HasKey("CategoryListId", "ExpensesListId");

                    b.HasIndex("ExpensesListId");

                    b.ToTable("CategoryExpense");
                });

            modelBuilder.Entity("CategoryIncome", b =>
                {
                    b.Property<int>("CategoryListId")
                        .HasColumnType("int");

                    b.Property<int>("IncomesListId")
                        .HasColumnType("int");

                    b.HasKey("CategoryListId", "IncomesListId");

                    b.HasIndex("IncomesListId");

                    b.ToTable("CategoryIncome");
                });

            modelBuilder.Entity("ExpenseRecurringExpense", b =>
                {
                    b.Property<int>("ExpenseListId")
                        .HasColumnType("int");

                    b.Property<int>("RecurringExpenseListId")
                        .HasColumnType("int");

                    b.HasKey("ExpenseListId", "RecurringExpenseListId");

                    b.HasIndex("RecurringExpenseListId");

                    b.ToTable("ExpenseRecurringExpense");
                });

            modelBuilder.Entity("IncomeIncomeSource", b =>
                {
                    b.Property<int>("IncomeSourceListId")
                        .HasColumnType("int");

                    b.Property<int>("IncomesId")
                        .HasColumnType("int");

                    b.HasKey("IncomeSourceListId", "IncomesId");

                    b.HasIndex("IncomesId");

                    b.ToTable("IncomeIncomeSource");
                });

            modelBuilder.Entity("CategoryExpense", b =>
                {
                    b.HasOne("BudgetHelperClassLibrary.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BudgetHelperClassLibrary.Models.Expense", null)
                        .WithMany()
                        .HasForeignKey("ExpensesListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CategoryIncome", b =>
                {
                    b.HasOne("BudgetHelperClassLibrary.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BudgetHelperClassLibrary.Models.Income", null)
                        .WithMany()
                        .HasForeignKey("IncomesListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExpenseRecurringExpense", b =>
                {
                    b.HasOne("BudgetHelperClassLibrary.Models.Expense", null)
                        .WithMany()
                        .HasForeignKey("ExpenseListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BudgetHelperClassLibrary.Models.RecurringExpense", null)
                        .WithMany()
                        .HasForeignKey("RecurringExpenseListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IncomeIncomeSource", b =>
                {
                    b.HasOne("BudgetHelperClassLibrary.Models.IncomeSource", null)
                        .WithMany()
                        .HasForeignKey("IncomeSourceListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BudgetHelperClassLibrary.Models.Income", null)
                        .WithMany()
                        .HasForeignKey("IncomesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
